export const avatarBlank = require('./avatarBlank.png')
export const searchEmpty = require('./searchEmpty.png')
export const companyIconSm = require('./company_icon.png')
export const logoSm = require('./logo_sm.png')
export const logoLg = require('./logo_lg.png')
export const downloadGooglePlay = require('./download_google_play.png')
export const downloadAppStore = require('./dowload_app_store.png')
export const loginFormBanner = require('./login_form_banner.png')
export const imageBlur =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/+F9PQAI8wNPvd7POQAAAABJRU5ErkJggg=='

export const empty = require('./empty.png')
export const cartEmpty = require('./cart_empty.png')

export const angryIcon = require('./angryIcon.png')
export const heartIcon = require('./heartIcon.png')
export const laughIcon = require('./laughIcon.png')
export const likeIcon = require('./likeIcon.png')
export const sadIcon = require('./sadIcon.png')
export const wowIcon = require('./wowIcon.png')
export const facebookIcon = require('./facebookIcon.png')
export const zaloIcon = require('./zaloIcon.png')
export const linkedIcon = require('./linkedinIcon.png')

export const enterInfo = require('./enterInfo.png')
export const takePhoto = require('./takePhoto.png')
export const getAdvise = require('./getAdvise.png')
export const discountBadge = require('./discount_badge.png')
export const emptyAddress = require('./empty_address.png')
export const error404 = require('./error_404.png')
export const thumbnailImage = require('./thumbnail.png')
export const orderDoneIcon = require('./order_done.png')
export const orderDoneBackground = require('./order_done_background.png')
export const categoryPromotionIcon = require('./category_promotion_icon.png')
export const giftIcon = require('./gift.png')
export const homeDecord = require('./home-decor.png')
export const medicine = require('./medicine.png')
export const protect = require('./protect.png')
export const returnBox = require('./return-box.png')
export const shipped = require('./shipped.png')
export const bigSale = require('./big-sale.png')

// image use in page "gioi-thieu.tsx"
export const introBanner = require('./abipha-banner-intro.png')
export const ability = require('./ability.png')
export const cooperate = require('./cooperate.png')
export const creative = require('./creative.png')
export const quality = require('./quality.png')
export const respect = require('./respect.png')
export const trust = require('./trust.png')
export const delivery = require('./delivery.png')
